config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :parkings
  root "parkings#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking.rb
class Parking < ApplicationRecord
  validates_presence_of :parking_type, :start_at
  validates_inclusion_of :parking_type, :in => ["guest","short-term","long-term"]

  validate :validate_end_at_with_amount
  belongs_to :user, :optional => true

  def validate_end_at_with_amount
    if ( end_at.present? && amount.blank? )
      errors.add(:amount, "have end_at must have amount")
    end

    if ( end_at.blank? && amount.present? )
      errors.add(:end_at, "have amount must have end_at")
    end
  end

  def duration
    ( end_at - start_at) / 60
  end

  def calculate_amount
      byebug
      if self.amount.blank? && self.start_at.present? && self.end_at.present?
        if self.user.blank?
          self.amount = calculate_guest_term_amount  # 一般费率
        elsif self.parking_type == "long-term"
            self.amount = calculate_long_term_amount # 短期费率
        elsif self.parking_type == "short-term"
          self.amount = calculate_short_term_amount  # 长期费率
        end
      end
    end

    def calculate_guest_term_amount
      if duration <= 60
        self.amount = 200
      else
        self.amount = 200 + ((duration - 60).to_f / 30).ceil * 100
      end
    end
    def calculate_short_term_amount
    if duration <= 60
      self.amount = 200
    else
      self.amount = 200 + ((duration - 60).to_f / 30).ceil * 50
    end
  end

  def calculate_long_term_amount
    # TODO
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :parkings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  # Step1:
  def new
    @parking = Parking.new
  end

  # Step2:
  def create
    @parking = Parking.new(:start_at => Time.now)
    if current_user
      @parking.parking_type = params[:parking][:parking_type]
      @parking.user = current_user
    else
      @parking.parking_type = "guest"
    end
    @parking.save!

    redirect_to parking_path(@parking)
  end

  # step3
  # step5
  def show
    @parking = Parking.find(params[:id])
  end

  # step4
  def update
    @parking = Parking.find(params[:id])
    @parking.end_at = Time.now
    @parking.calculate_amount

    @parking.save!

    redirect_to parking_path(@parking)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>

    <% if flash[:alert] %>
      <%= flash[:alert] %>
    <% end %>

    <% if current_user %>
      <%= link_to('logout', destroy_user_session_path, :method => :delete) %>
      <%= link_to('change password', edit_registration_path(:user)) %>
    <% else %>
      <%= link_to('registration', new_registration_path(:user)) %> |
      <%= link_to('logon',new_session_path(:user)) %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/parkings/new.html.erb
<h1>amount compute</h1>

<%= form_for @parking do |f| %>
  <% if current_user %>

    <label>
      <%= f.radio_button :parking_type, "short-term" %>short-term
    </label>

    <label>
      <%= f.radio_button :parking_type, "long-term" %>long-term
    </label>
  <% else %>
    common
  <% end %>
  <p><%= f.submit "start charging" %></p>

<% end %>

app/views/parkings/show.html.erb
<h1>amount compute</h1>

<% if @parking.amount.present? #end, show amount %>
  <p>parking_type<%= @parking.parking_type %></p>
  <p>from <%= @parking.start_at %>to <%= @parking.end_at %></p>
  <p> <%= @parking.duration %> minute</p>
  <p><%= number_to_currency(@parking.amount.to_f / 100, :unit => "¥") %> 元</p>

  <p><%= link_to "continue park",new_parking_path  %></p>

<% else # not end %>
  <%= form_for @parking do |f| %>

    <p><%= f.submit "end" %></p>

  <% end %>
<% end %>